### ISSUE TITLE
Can provide released pdf or epub?

### ISSUE THREAD

**Issue by cxz66666** [xuxiaodong/usingcli-book#1]
I found this book is very suitable for fresh man who begin to learning CLI. But can you provide a release pdf or epub format file by github action or release page, even can provide those file in root path? R language is rare and not installed to most audiences 🥲

**Comment by DaVinci42** [comment]
or please consider Github Action to generate PDF/ePub automatically for every commit

**Comment by kanna5** [comment]
I managed to generate the PDF with the `texlive/texlive` docker image.

```bash
git clone https://github.com/xuxiaodong/usingcli-book.git
cd usingcli-book
sudo docker run -it --rm -v "$(pwd):/cwd" --workdir /cwd texlive/texlive:latest-small bash
```

Then inside the docker container, run

```bash
apt update
apt install build-essential file pandoc r-base-dev
export MAKEFLAGS=" -j $(nproc)"
```

Run `R` and type in these commands

```R
install.packages("rmarkdown")
install.packages("bookdown")
```

Exit R, run `make pdf`

The generated PDF file can be found inside the `_book` directory.

**Comment by cxz66666** [comment]
> I managed to generate the PDF with the texlive/texlive docker image.

@kanna5  This is a nice example for a fresh man to R language! Thank you!

**Comment by xuxiaodong** [comment]
@cxz66666 You can download the pdf/epub at: https://github.com/xuxiaodong/usingcli-book/releases/
